package keycredential

import (
	"context"
	"fmt"
	"slices"
	"time"

	"github.com/google/uuid"
	msgraph "github.com/nais/msgraph.go/v1.0"

	"github.com/nais/azureator/pkg/azure/client/application"
	"github.com/nais/azureator/pkg/azure/credentials"
	"github.com/nais/azureator/pkg/azure/util"
	"github.com/nais/azureator/pkg/transaction"
	"github.com/nais/azureator/pkg/util/crypto"
)

type KeyCredential interface {
	Add(tx transaction.Transaction) (*credentials.AddedKeyCredentialSet, error)
	DeleteExpired(tx transaction.Transaction) error
	DeleteUnused(tx transaction.Transaction) error
	Purge(tx transaction.Transaction) error
	Rotate(tx transaction.Transaction) (*msgraph.KeyCredential, *crypto.Jwk, error)
}

type keyCredential struct {
	Client
}

type Client interface {
	Application() application.Application
}

// Workaround to include empty array of KeyCredentials in JSON serialization.
// The autogenerated library code uses 'omitempty' for KeyCredentials, which when empty
// leaves the list of redirect URIs unchanged and non-empty.
type app struct {
	msgraph.DirectoryObject
	KeyCredentials []msgraph.KeyCredential `json:"keyCredentials"`
}

func NewKeyCredential(client Client) KeyCredential {
	return keyCredential{Client: client}
}

func (k keyCredential) Add(tx transaction.Transaction) (*credentials.AddedKeyCredentialSet, error) {
	existing, err := k.Application().Get(tx)
	if err != nil {
		return nil, err
	}

	currentKeyCredential, currentJwk, err := k.new(tx)
	if err != nil {
		return nil, err
	}

	nextKeyCredential, nextJwk, err := k.new(tx)
	if err != nil {
		return nil, err
	}

	keyCredentials := append(slices.Clone(existing.KeyCredentials), *currentKeyCredential, *nextKeyCredential)
	if err := k.patch(tx, keyCredentials); err != nil {
		return nil, fmt.Errorf("updating application with keycredential set: %w", err)
	}

	return &credentials.AddedKeyCredentialSet{
		Current: credentials.AddedKeyCredential{
			KeyCredential: *currentKeyCredential,
			Jwk:           *currentJwk,
		},
		Next: credentials.AddedKeyCredential{
			KeyCredential: *nextKeyCredential,
			Jwk:           *nextJwk,
		},
	}, nil
}

func (k keyCredential) DeleteExpired(tx transaction.Transaction) error {
	return k.removeKeys(tx, "expired", func(keys []msgraph.KeyCredential) (kept, removed []msgraph.KeyCredential) {
		now := time.Now()
		for _, cred := range keys {
			if cred.EndDateTime == nil || cred.EndDateTime.After(now) {
				kept = append(kept, cred)
			} else {
				removed = append(removed, cred)
			}
		}
		return kept, removed
	})
}

func (k keyCredential) DeleteUnused(tx transaction.Transaction) error {
	return k.removeKeys(tx, "unused", func(keys []msgraph.KeyCredential) ([]msgraph.KeyCredential, []msgraph.KeyCredential) {
		return filterRevokedKeys(tx, keys)
	})
}

func (k keyCredential) Purge(tx transaction.Transaction) error {
	return k.patch(tx, []msgraph.KeyCredential{})
}

// Rotate generates a new set of key credentials, removing any key not in use (as indicated by AzureAdApplication.Status.CertificateKeyIds).
// Except new applications, there should always be at least two active keys available at any given time so that running applications are not interfered with.
func (k keyCredential) Rotate(tx transaction.Transaction) (*msgraph.KeyCredential, *crypto.Jwk, error) {
	existing, err := k.Application().Get(tx)
	if err != nil {
		return nil, nil, err
	}
	keysInUse, removed := filterRevokedKeys(tx, existing.KeyCredentials)
	logRemoved(tx, "unused", removed)

	keyCredential, jwk, err := k.new(tx)
	if err != nil {
		return nil, nil, err
	}

	keysInUse = append(keysInUse, *keyCredential)

	if err := k.patch(tx, keysInUse); err != nil {
		return nil, nil, fmt.Errorf("updating application with keycredential: %w", err)
	}

	return keyCredential, jwk, nil
}

func (k keyCredential) removeKeys(tx transaction.Transaction, reason string, filter func([]msgraph.KeyCredential) (kept, removed []msgraph.KeyCredential)) error {
	existing, err := k.Application().Get(tx)
	if err != nil {
		return err
	}
	kept, removed := filter(existing.KeyCredentials)
	if len(removed) == 0 {
		return nil
	}
	logRemoved(tx, reason, removed)
	if err := k.patch(tx, kept); err != nil {
		return fmt.Errorf("removing %s key credentials: %w", reason, err)
	}
	return nil
}

// patch replaces the application's key credentials. Graph omits certificate bytes on reads,
// but rejects entries without them. patch takes the bytes from the managed Secrets and drops
// certificates that no Secret holds, because nobody has their private key.
func (k keyCredential) patch(tx transaction.Transaction, keyCredentials []msgraph.KeyCredential) error {
	keyCredentials, unmanaged := withKeyBytes(keyCredentials, tx.Secrets.Certificates)
	logRemoved(tx, "unmanaged", unmanaged)

	var payload any = util.EmptyApplication().Keys(keyCredentials).Build()
	if len(keyCredentials) == 0 {
		payload = &app{KeyCredentials: []msgraph.KeyCredential{}}
	}
	return credentials.RetryGraph(tx.Ctx, &tx.Logger, "patch key credentials", func(ctx context.Context) error {
		return k.Application().Patch(ctx, tx.Instance.GetObjectId(), payload)
	})
}

func (k keyCredential) new(tx transaction.Transaction) (*msgraph.KeyCredential, *crypto.Jwk, error) {
	jwkPair, err := crypto.GenerateJwk(tx.Instance, tx.ClusterName)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to generate JWK pair for application: %w", err)
	}

	newKeyCredential := k.toKeyCredential(jwkPair)

	return &newKeyCredential, &jwkPair, nil
}

func (k keyCredential) toKeyCredential(jwkPair crypto.Jwk) msgraph.KeyCredential {
	keyId := msgraph.UUID(uuid.New().String())
	keyBase64 := msgraph.Binary(jwkPair.PublicPem)
	return msgraph.KeyCredential{
		KeyID:       &keyId,
		DisplayName: new(util.DisplayName(time.Now())),
		Type:        new("AsymmetricX509Cert"),
		Usage:       new("Verify"),
		Key:         &keyBase64,
	}
}

// filterRevokedKeys splits keys into kept and removed. It keeps the keys that the managed Secrets use.
func filterRevokedKeys(tx transaction.Transaction, keyCredentials []msgraph.KeyCredential) (kept, removed []msgraph.KeyCredential) {
	keyIDsInUse := append(
		slices.Clone(tx.Secrets.KeyIDs.Used.Certificate),
		tx.Secrets.LatestCredentials.Set.Current.Certificate.KeyId,
		tx.Secrets.LatestCredentials.Set.Next.Certificate.KeyId,
	)
	for _, cred := range keyCredentials {
		if slices.Contains(keyIDsInUse, keyID(cred)) {
			kept = append(kept, cred)
		} else {
			removed = append(removed, cred)
		}
	}
	return kept, removed
}

// withKeyBytes fills missing key bytes from keys by key ID. It drops the entries that remain without key bytes.
func withKeyBytes(keyCredentials []msgraph.KeyCredential, keys map[string][]byte) (kept, dropped []msgraph.KeyCredential) {
	for _, cred := range keyCredentials {
		if cred.Key == nil || len(*cred.Key) == 0 {
			key, ok := keys[keyID(cred)]
			if !ok {
				dropped = append(dropped, cred)
				continue
			}
			cred.Key = new(msgraph.Binary(key))
		}
		kept = append(kept, cred)
	}
	return kept, dropped
}

func keyID(cred msgraph.KeyCredential) string {
	if cred.KeyID == nil {
		return ""
	}
	return string(*cred.KeyID)
}

func logRemoved(tx transaction.Transaction, reason string, removed []msgraph.KeyCredential) {
	for _, cred := range removed {
		if cred.DisplayName != nil && cred.KeyID != nil {
			tx.Logger.Debugf("revoking %s key credential '%s' (ID: %s)", reason, *cred.DisplayName, *cred.KeyID)
		}
	}
}
