package client

import (
	"fmt"

	"github.com/nais/azureator/pkg/azure"
	"github.com/nais/azureator/pkg/azure/util"
	msgraph "github.com/yaegashi/msgraph.go/v1.0"
)

// Workaround to include empty array of RedirectUris in JSON serialization.
// The autogenerated library code uses 'omitempty' for RedirectUris, which when empty
// leaves the list of redirect URIs unchanged and non-empty.
type webApi struct {
	RedirectUris []string `json:"redirectUris"`
}

type redirectUri struct {
	application
}

func (a application) redirectUri() redirectUri {
	return redirectUri{a}
}

func (r redirectUri) update(tx azure.Transaction) error {
	objectId := tx.Instance.Status.ObjectId
	app := &struct {
		msgraph.DirectoryObject
		Web webApi `json:"web"`
	}{
		Web: webApi{
			RedirectUris: util.GetReplyUrlsStringSlice(tx.Instance),
		},
	}
	if err := r.patch(tx.Ctx, objectId, app); err != nil {
		return fmt.Errorf("failed to update redirect URIs: %w", err)
	}
	return nil
}
