@startuml component
title Azurerator Sequence Flow
skinparam maxMessageSize 300
autonumber

actor developer as "Developer"
control azurerator as "Azurerator"

box "Cluster resources"
participant AzureAdApplication
participant Secret
end box

participant azuread as "Azure AD"

==On create / update==
developer -> AzureAdApplication: Apply config

loop forever
	azurerator -> AzureAdApplication: watch for updates
end

azurerator -> azuread: check if application exists
azurerator -> azuread: register / update application
azurerator -> azurerator: generate new set of credentials
azurerator -> azuread: register new credentials

group application already exists in AAD
    azurerator -> Secret: fetch existing credentials
    azurerator -> azuread: invalidate older, non-used credentials
end

azurerator -> AzureAdApplication: update status subresource
azurerator -> Secret: inject credentials and metadata

==On deletion==
    developer -> AzureAdApplication: delete
    azurerator -> Secret: delete
    azurerator -> azuread: delete

@enduml
